kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: el-ci-pipeline-el
  labels:
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: Triggers
    eventlistener: ci-pipeline-el
  annotations:
    openshift.io/host.generated: 'true'
spec:
  to:
    kind: Service
    name: el-ci-pipeline-el
    weight: 100
  port:
    targetPort: http-listener
  wildcardPolicy: None
